export const ErrorType = {
    NOT_FOUND: 'NOT_FOUND',
    INVALID_DATA: 'INVALID_DATA',
    POST_ERROR: 'POST_ERROR',
    DELETE_ERROR: 'DELETE_ERROR',
    UPDATE_ERROR: 'UPDATE_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
  }
  